// Production Repository adapter backed by Prisma/Postgres.
//
// The Prisma client type is GENERATED by `npx prisma generate`; to keep this
// package compiling before generation, the client is injected as a structural
// `PrismaClientLike` shape rather than importing generated types. Wire the real
// `new PrismaClient()` in the composition root (src/index.ts).
//
// The critical method is `recordLedgerEntryIfAbsent`: idempotency is enforced by
// the `@@unique([runId, stepIndex, toolCallId])` constraint — a duplicate insert
// raises Prisma error P2002, which we translate into a no-op `false`.

import {
  Agent,
  AgentType,
  ChatMessageRecord,
  DeadLetterRecord,
  MemoryKind,
  MemoryRecord,
  Org,
  Run,
  RunStatus,
  Step,
} from '../domain/types';
import { Repository } from '../ports/repository';

// Minimal structural view of the generated client (delegates typed loosely).
export interface PrismaClientLike {
  org: any;
  agent: any;
  promptVersion: any;
  run: any;
  step: any;
  agentMemory: any;
  deadLetter: any;
  auditLog: any;
  chatMessage: any;
  $transaction: <T>(fn: (tx: PrismaClientLike) => Promise<T>) => Promise<T>;
}

export class PrismaRepository implements Repository {
  constructor(private readonly db: PrismaClientLike) {}

  async getOrg(orgId: string): Promise<Org | null> {
    const o = await this.db.org.findUnique({ where: { id: orgId } });
    return o
      ? { id: o.id, name: o.name }
      : null;
  }

  async getAgent(agentId: string): Promise<Agent | null> {
    const a = await this.db.agent.findUnique({
      where: { id: agentId },
      include: { currentVersion: true },
    });
    if (!a) return null;
    return {
      id: a.id,
      orgId: a.orgId,
      name: a.name,
      type: a.type,
      systemPrompt: a.currentVersion?.systemPrompt ?? '',
      allowedTools: a.allowedTools ?? [],
    };
  }

  async findAgentByType(orgId: string, type: AgentType): Promise<Agent | null> {
    const a = await this.db.agent.findFirst({
      where: { orgId, type },
      include: { currentVersion: true },
    });
    if (!a) return null;
    return {
      id: a.id,
      orgId: a.orgId,
      name: a.name,
      type: a.type,
      systemPrompt: a.currentVersion?.systemPrompt ?? '',
      allowedTools: a.allowedTools ?? [],
    };
  }

  async createAgent(input: {
    orgId: string;
    name: string;
    type: AgentType;
    systemPrompt: string;
    allowedTools?: string[];
  }): Promise<Agent> {
    const agent = await this.db.agent.create({
      data: { orgId: input.orgId, name: input.name, type: input.type, allowedTools: input.allowedTools ?? [] },
    });
    const pv = await this.db.promptVersion.create({
      data: { agentId: agent.id, version: 1, systemPrompt: input.systemPrompt },
    });
    await this.db.agent.update({ where: { id: agent.id }, data: { currentVersionId: pv.id } });
    return {
      id: agent.id,
      orgId: agent.orgId,
      name: agent.name,
      type: agent.type,
      systemPrompt: input.systemPrompt,
      allowedTools: agent.allowedTools ?? [],
    };
  }

  async listAgents(orgId: string): Promise<Agent[]> {
    const rows = await this.db.agent.findMany({
      where: { orgId },
      include: { currentVersion: true },
      orderBy: { createdAt: 'asc' },
    });
    return rows.map((a: any) => ({
      id: a.id,
      orgId: a.orgId,
      name: a.name,
      type: a.type,
      systemPrompt: a.currentVersion?.systemPrompt ?? '',
      allowedTools: a.allowedTools ?? [],
    }));
  }

  async getRun(runId: string): Promise<Run | null> {
    const r = await this.db.run.findUnique({ where: { id: runId } });
    return r ? this.mapRun(r) : null;
  }

  async createRun(run: Run): Promise<Run> {
    // Idempotent by id (orchestration retries reuse deterministic child ids).
    await this.db.run.upsert({
      where: { id: run.id },
      update: {},
      create: {
        id: run.id,
        orgId: run.orgId,
        agentId: run.agentId,
        status: run.status,
        input: run.input as any,
        attempts: run.attempts,
        parentRunId: run.parentRunId,
      },
    });
    return run;
  }

  async listChildRuns(parentRunId: string): Promise<Run[]> {
    // Deterministic order for the team-discussion feed.
    const rows = await this.db.run.findMany({
      where: { parentRunId },
      orderBy: { createdAt: 'asc' },
    });
    return rows.map((r: any) => this.mapRun(r));
  }

  async listRunsByOrg(
    orgId: string,
    opts: { agentId?: string; limit?: number } = {},
  ): Promise<Run[]> {
    const rows = await this.db.run.findMany({
      where: { orgId, ...(opts.agentId ? { agentId: opts.agentId } : {}) },
      orderBy: { createdAt: 'desc' },
      ...(opts.limit ? { take: opts.limit } : {}),
    });
    // Callers expect ascending creation order.
    return rows.reverse().map((r: any) => this.mapRun(r));
  }

  // --- Chat thread (dialog memory) ---
  async appendChatMessage(msg: ChatMessageRecord): Promise<ChatMessageRecord> {
    const row = await this.db.chatMessage.create({
      data: {
        orgId: msg.orgId,
        agentId: msg.agentId,
        role: msg.role,
        text: msg.text,
        runId: msg.runId,
      },
    });
    return this.mapChatMessage(row);
  }

  async appendChatReplyIfAbsent(
    msg: ChatMessageRecord & { runId: string },
  ): Promise<boolean> {
    // Idempotency via the (runId, role) unique index: a duplicate insert raises
    // Prisma P2002, which we translate into a no-op `false` (race-safe backfill).
    try {
      await this.appendChatMessage(msg);
      return true;
    } catch (err: any) {
      if (err?.code === 'P2002') return false;
      throw err;
    }
  }

  async listChatMessages(
    orgId: string,
    agentId: string,
    limit = 100,
  ): Promise<ChatMessageRecord[]> {
    const rows = await this.db.chatMessage.findMany({
      where: { orgId, agentId },
      orderBy: { createdAt: 'desc' },
      take: limit,
    });
    return rows.reverse().map((m: any) => this.mapChatMessage(m));
  }

  async toggleChatReaction(
    orgId: string,
    agentId: string,
    messageId: string,
    emoji: string,
  ): Promise<ChatMessageRecord | null> {
    const row = await this.db.chatMessage.findUnique({ where: { id: messageId } });
    if (!row || row.orgId !== orgId || row.agentId !== agentId) return null;
    const current: string[] = Array.isArray(row.reactions) ? row.reactions : [];
    const set = new Set(current);
    if (set.has(emoji)) set.delete(emoji);
    else set.add(emoji);
    const next = [...set];
    const updated = await this.db.chatMessage.update({
      where: { id: messageId },
      data: { reactions: next as any },
    });
    return this.mapChatMessage(updated);
  }

  private mapChatMessage(m: any): ChatMessageRecord {
    return {
      id: m.id,
      orgId: m.orgId,
      agentId: m.agentId,
      role: m.role,
      text: m.text,
      runId: m.runId ?? undefined,
      reactions: Array.isArray(m.reactions) ? m.reactions : undefined,
      createdAt: m.createdAt instanceof Date ? m.createdAt.getTime() : m.createdAt,
    };
  }

  private mapRun(r: any): Run {
    return {
      id: r.id,
      orgId: r.orgId,
      agentId: r.agentId,
      status: r.status,
      input: r.input,
      output: r.output ?? undefined,
      error: r.error ?? undefined,
      attempts: r.attempts,
      parentRunId: r.parentRunId ?? undefined,
    };
  }

  async updateRunStatus(
    runId: string,
    status: RunStatus,
    patch: Partial<Run> = {},
  ): Promise<void> {
    await this.db.run.update({
      where: { id: runId },
      data: {
        status,
        ...(patch.output !== undefined ? { output: patch.output as any } : {}),
        ...(patch.error !== undefined ? { error: patch.error } : {}),
      },
    });
  }

  async incrementRunAttempts(runId: string): Promise<number> {
    const r = await this.db.run.update({
      where: { id: runId },
      data: { attempts: { increment: 1 } },
    });
    return r.attempts;
  }

  async appendStep(step: Step): Promise<void> {
    await this.db.step.upsert({
      where: { runId_index: { runId: step.runId, index: step.index } },
      create: {
        runId: step.runId,
        index: step.index,
        role: step.role,
        toolName: step.toolName,
        toolCallId: step.toolCallId,
        input: step.input as any,
        output: step.output as any,
        latencyMs: step.latencyMs,
        tokensIn: step.tokensIn,
        tokensOut: step.tokensOut,
      },
      update: {
        output: step.output as any,
        latencyMs: step.latencyMs,
        tokensIn: step.tokensIn,
        tokensOut: step.tokensOut,
      },
    });
  }

  async listSteps(runId: string): Promise<Step[]> {
    const rows = await this.db.step.findMany({
      where: { runId },
      orderBy: { index: 'asc' },
    });
    return rows.map((s: any) => ({
      runId: s.runId,
      index: s.index,
      role: s.role,
      toolName: s.toolName ?? undefined,
      toolCallId: s.toolCallId ?? undefined,
      input: s.input ?? undefined,
      output: s.output ?? undefined,
      latencyMs: s.latencyMs ?? undefined,
      tokensIn: s.tokensIn ?? undefined,
      tokensOut: s.tokensOut ?? undefined,
    }));
  }

  async appendMemory(memory: MemoryRecord): Promise<void> {
    await this.db.agentMemory.create({
      data: {
        agentId: memory.agentId,
        kind: memory.kind,
        content: memory.content as any,
        runId: memory.runId,
      },
    });
  }

  async listMemories(agentId: string, kinds?: MemoryKind[]): Promise<MemoryRecord[]> {
    const rows = await this.db.agentMemory.findMany({
      where: { agentId, ...(kinds ? { kind: { in: kinds } } : {}) },
      orderBy: { createdAt: 'desc' },
    });
    return rows.map((m: any) => ({
      id: m.id,
      agentId: m.agentId,
      kind: m.kind,
      content: m.content,
      runId: m.runId ?? undefined,
      createdAt: m.createdAt instanceof Date ? m.createdAt.getTime() : m.createdAt,
    }));
  }


  async recordDeadLetter(record: DeadLetterRecord): Promise<void> {
    await this.db.deadLetter.create({
      data: {
        runId: record.runId,
        payload: record.payload as any,
        failureReason: record.failureReason,
        attempts: record.attempts,
      },
    });
  }

  async listDeadLetters(): Promise<DeadLetterRecord[]> {
    const rows = await this.db.deadLetter.findMany({ where: { requeuedAt: null } });
    return rows.map((d: any) => ({
      runId: d.runId,
      payload: d.payload,
      failureReason: d.failureReason,
      attempts: d.attempts,
    }));
  }

  async markDeadLetterRequeued(runId: string): Promise<void> {
    await this.db.deadLetter.updateMany({
      where: { runId, requeuedAt: null },
      data: { requeuedAt: new Date() },
    });
  }

  async audit(entry: {
    orgId: string;
    runId?: string;
    actor: string;
    action: string;
    meta?: unknown;
  }): Promise<void> {
    await this.db.auditLog.create({
      data: {
        orgId: entry.orgId,
        runId: entry.runId,
        actor: entry.actor,
        action: entry.action,
        meta: entry.meta as any,
      },
    });
  }
}
