// Production Repository adapter backed by Prisma/Postgres.
//
// The Prisma client type is GENERATED by `npx prisma generate`; to keep this
// package compiling before generation, the client is injected as a structural
// `PrismaClientLike` shape rather than importing generated types. Wire the real
// `new PrismaClient()` in the composition root (src/index.ts).
//
// The critical method is `recordLedgerEntryIfAbsent`: idempotency is enforced by
// the `@@unique([runId, stepIndex, toolCallId])` constraint — a duplicate insert
// raises Prisma error P2002, which we translate into a no-op `false`.

import {
  Agent,
  AgentType,
  CreditGrant,
  DeadLetterRecord,
  LedgerEntry,
  MemoryKind,
  MemoryRecord,
  Org,
  Run,
  RunStatus,
  Step,
} from '../domain/types';
import { Repository } from '../ports/repository';

// Minimal structural view of the generated client (delegates typed loosely).
export interface PrismaClientLike {
  org: any;
  agent: any;
  run: any;
  step: any;
  agentMemory: any;
  creditLedger: any;
  creditGrant: any;
  deadLetter: any;
  auditLog: any;
  $transaction: <T>(fn: (tx: PrismaClientLike) => Promise<T>) => Promise<T>;
}

export class PrismaRepository implements Repository {
  constructor(private readonly db: PrismaClientLike) {}

  async getOrg(orgId: string): Promise<Org | null> {
    const o = await this.db.org.findUnique({ where: { id: orgId } });
    return o
      ? { id: o.id, name: o.name, creditBalance: o.creditBalance }
      : null;
  }

  async getAgent(agentId: string): Promise<Agent | null> {
    const a = await this.db.agent.findUnique({
      where: { id: agentId },
      include: { currentVersion: true },
    });
    if (!a) return null;
    return {
      id: a.id,
      orgId: a.orgId,
      name: a.name,
      type: a.type,
      systemPrompt: a.currentVersion?.systemPrompt ?? '',
    };
  }

  async findAgentByType(orgId: string, type: AgentType): Promise<Agent | null> {
    const a = await this.db.agent.findFirst({
      where: { orgId, type },
      include: { currentVersion: true },
    });
    if (!a) return null;
    return {
      id: a.id,
      orgId: a.orgId,
      name: a.name,
      type: a.type,
      systemPrompt: a.currentVersion?.systemPrompt ?? '',
    };
  }

  async getRun(runId: string): Promise<Run | null> {
    const r = await this.db.run.findUnique({ where: { id: runId } });
    return r ? this.mapRun(r) : null;
  }

  async createRun(run: Run): Promise<Run> {
    // Idempotent by id (orchestration retries reuse deterministic child ids).
    await this.db.run.upsert({
      where: { id: run.id },
      update: {},
      create: {
        id: run.id,
        orgId: run.orgId,
        agentId: run.agentId,
        status: run.status,
        input: run.input as any,
        creditsUsed: run.creditsUsed,
        attempts: run.attempts,
        parentRunId: run.parentRunId,
      },
    });
    return run;
  }

  async listChildRuns(parentRunId: string): Promise<Run[]> {
    const rows = await this.db.run.findMany({ where: { parentRunId } });
    return rows.map((r: any) => this.mapRun(r));
  }

  async listRunsByOrg(orgId: string): Promise<Run[]> {
    const rows = await this.db.run.findMany({ where: { orgId } });
    return rows.map((r: any) => this.mapRun(r));
  }

  private mapRun(r: any): Run {
    return {
      id: r.id,
      orgId: r.orgId,
      agentId: r.agentId,
      status: r.status,
      input: r.input,
      output: r.output ?? undefined,
      error: r.error ?? undefined,
      creditsUsed: r.creditsUsed,
      attempts: r.attempts,
      parentRunId: r.parentRunId ?? undefined,
    };
  }

  async updateRunStatus(
    runId: string,
    status: RunStatus,
    patch: Partial<Run> = {},
  ): Promise<void> {
    await this.db.run.update({
      where: { id: runId },
      data: {
        status,
        ...(patch.output !== undefined ? { output: patch.output as any } : {}),
        ...(patch.error !== undefined ? { error: patch.error } : {}),
        ...(patch.creditsUsed !== undefined
          ? { creditsUsed: patch.creditsUsed }
          : {}),
      },
    });
  }

  async incrementRunAttempts(runId: string): Promise<number> {
    const r = await this.db.run.update({
      where: { id: runId },
      data: { attempts: { increment: 1 } },
    });
    return r.attempts;
  }

  async appendStep(step: Step): Promise<void> {
    await this.db.step.upsert({
      where: { runId_index: { runId: step.runId, index: step.index } },
      create: {
        runId: step.runId,
        index: step.index,
        role: step.role,
        toolName: step.toolName,
        toolCallId: step.toolCallId,
        input: step.input as any,
        output: step.output as any,
        latencyMs: step.latencyMs,
        tokensIn: step.tokensIn,
        tokensOut: step.tokensOut,
      },
      update: {
        output: step.output as any,
        latencyMs: step.latencyMs,
        tokensIn: step.tokensIn,
        tokensOut: step.tokensOut,
      },
    });
  }

  async listSteps(runId: string): Promise<Step[]> {
    const rows = await this.db.step.findMany({
      where: { runId },
      orderBy: { index: 'asc' },
    });
    return rows.map((s: any) => ({
      runId: s.runId,
      index: s.index,
      role: s.role,
      toolName: s.toolName ?? undefined,
      toolCallId: s.toolCallId ?? undefined,
      input: s.input ?? undefined,
      output: s.output ?? undefined,
      latencyMs: s.latencyMs ?? undefined,
      tokensIn: s.tokensIn ?? undefined,
      tokensOut: s.tokensOut ?? undefined,
    }));
  }

  async appendMemory(memory: MemoryRecord): Promise<void> {
    await this.db.agentMemory.create({
      data: {
        agentId: memory.agentId,
        kind: memory.kind,
        content: memory.content as any,
        runId: memory.runId,
      },
    });
  }

  async listMemories(agentId: string, kinds?: MemoryKind[]): Promise<MemoryRecord[]> {
    const rows = await this.db.agentMemory.findMany({
      where: { agentId, ...(kinds ? { kind: { in: kinds } } : {}) },
      orderBy: { createdAt: 'desc' },
    });
    return rows.map((m: any) => ({
      id: m.id,
      agentId: m.agentId,
      kind: m.kind,
      content: m.content,
      runId: m.runId ?? undefined,
      createdAt: m.createdAt instanceof Date ? m.createdAt.getTime() : m.createdAt,
    }));
  }

  async recordLedgerEntryIfAbsent(entry: LedgerEntry): Promise<boolean> {
    try {
      await this.db.$transaction(async (tx) => {
        await tx.creditLedger.create({
          data: {
            orgId: entry.orgId,
            runId: entry.runId,
            stepIndex: entry.stepIndex,
            toolCallId: entry.toolCallId,
            amount: entry.amount,
            reason: entry.reason,
          },
        });
        await tx.org.update({
          where: { id: entry.orgId },
          data: { creditBalance: { increment: entry.amount } },
        });
        await tx.run.update({
          where: { id: entry.runId },
          data: { creditsUsed: { increment: Math.abs(entry.amount) } },
        });
      });
      return true;
    } catch (err: any) {
      // P2002 = unique constraint violation => already charged => no-op.
      if (err?.code === 'P2002') return false;
      throw err;
    }
  }

  async getRunCreditsUsed(runId: string): Promise<number> {
    const agg = await this.db.creditLedger.aggregate({
      where: { runId },
      _sum: { amount: true },
    });
    return agg?._sum?.amount ?? 0;
  }

  async recordCreditGrantIfAbsent(grant: CreditGrant): Promise<boolean> {
    try {
      await this.db.$transaction(async (tx) => {
        await tx.creditGrant.create({
          data: {
            orgId: grant.orgId,
            source: grant.source,
            externalId: grant.externalId,
            amount: grant.amount,
          },
        });
        await tx.org.update({
          where: { id: grant.orgId },
          data: { creditBalance: { increment: grant.amount } },
        });
      });
      return true;
    } catch (err: any) {
      if (err?.code === 'P2002') return false; // duplicate (source, externalId)
      throw err;
    }
  }

  async recordDeadLetter(record: DeadLetterRecord): Promise<void> {
    await this.db.deadLetter.create({
      data: {
        runId: record.runId,
        payload: record.payload as any,
        failureReason: record.failureReason,
        attempts: record.attempts,
      },
    });
  }

  async listDeadLetters(): Promise<DeadLetterRecord[]> {
    const rows = await this.db.deadLetter.findMany({ where: { requeuedAt: null } });
    return rows.map((d: any) => ({
      runId: d.runId,
      payload: d.payload,
      failureReason: d.failureReason,
      attempts: d.attempts,
    }));
  }

  async markDeadLetterRequeued(runId: string): Promise<void> {
    await this.db.deadLetter.updateMany({
      where: { runId, requeuedAt: null },
      data: { requeuedAt: new Date() },
    });
  }

  async audit(entry: {
    orgId: string;
    runId?: string;
    actor: string;
    action: string;
    meta?: unknown;
  }): Promise<void> {
    await this.db.auditLog.create({
      data: {
        orgId: entry.orgId,
        runId: entry.runId,
        actor: entry.actor,
        action: entry.action,
        meta: entry.meta as any,
      },
    });
  }
}
