// Composition root. Wires production adapters into the runtime/worker.
//
// Planes:
//   - Control Plane: enqueues RunJobs (HTTP API would call queue.enqueue) — not
//     included in the MVP; see docs/SPEC.md.
//   - Execution Plane: the worker (startWorker) drains the queue and runs agents.
//   - Billing Plane: the Repository + Ledger (idempotent credit accounting).

import { loadConfig } from './config';
import { Ledger } from './billing/ledger';
import { ToolRegistry } from './tools/registry';
import { httpRequestTool } from './tools/httpRequest';
import { codeExecTool } from './tools/codeExec';
import { WorkerDeps } from './worker/worker';
import { PrismaRepository, PrismaClientLike } from './adapters/repo.prisma';
import { BullMQQueue } from './adapters/queue.bullmq';
import { AnthropicModelProvider } from './adapters/model.anthropic';

export function buildToolRegistry(): ToolRegistry {
  const tools = new ToolRegistry();
  tools.register(httpRequestTool);
  tools.register(codeExecTool);
  return tools;
}

export interface App {
  workerDeps: WorkerDeps;
}

export function buildApp(): App {
  const config = loadConfig();

  // Prisma client is generated by `npx prisma generate`; require lazily so this
  // module compiles before generation.
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { PrismaClient } = require('@prisma/client');
  const repo = new PrismaRepository(new PrismaClient() as PrismaClientLike);

  const queue = new BullMQQueue({ redisUrl: config.redisUrl });
  const model = new AnthropicModelProvider({
    apiKey: config.anthropicApiKey,
    model: config.anthropicModel,
  });
  const tools = buildToolRegistry();
  const ledger = new Ledger(repo);

  return {
    workerDeps: {
      queue,
      repo,
      model,
      tools,
      ledger,
      allowlistDomains: config.allowlistDomains,
    },
  };
}

export { startWorker } from './worker/worker';
