// Composition root. Wires production adapters into the runtime/worker and the
// Control Plane.
//
// Planes:
//   - Control Plane: the ControlPlane API (src/api) creates runs, exposes status
//     + observability, manages the DLQ, and handles billing top-ups.
//   - Execution Plane: the worker (startWorker) drains the queue and runs agents.
//   - Billing Plane: the Repository + Ledger (idempotent credit accounting).

import { loadConfig } from './config';
import { Ledger } from './billing/ledger';
import { ToolRegistry } from './tools/registry';
import { httpRequestTool } from './tools/httpRequest';
import { codeExecTool } from './tools/codeExec';
import { WorkerDeps } from './worker/worker';
import { PrismaRepository, PrismaClientLike } from './adapters/repo.prisma';
import { BullMQQueue } from './adapters/queue.bullmq';
import { AnthropicModelProvider } from './adapters/model.anthropic';
import { ModelPlanner } from './orchestrator/planner';
import { InMemoryEventBus } from './events/bus';
import { RepositoryMemoryStore } from './adapters/memory.repo';
import { Observability } from './observability/metrics';
import { StripePaymentProvider } from './adapters/payments.stripe';
import { ControlPlane } from './api/controlPlane';

export function buildToolRegistry(): ToolRegistry {
  const tools = new ToolRegistry();
  tools.register(httpRequestTool);
  tools.register(codeExecTool);
  return tools;
}

export interface App {
  workerDeps: WorkerDeps;
  controlPlane: ControlPlane;
}

export function buildApp(): App {
  const config = loadConfig();

  // Prisma client is generated by `npx prisma generate`; require lazily so this
  // module compiles before generation.
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { PrismaClient } = require('@prisma/client');
  const repo = new PrismaRepository(new PrismaClient() as PrismaClientLike);

  const queue = new BullMQQueue({ redisUrl: config.redisUrl });
  const model = new AnthropicModelProvider({
    apiKey: config.anthropicApiKey,
    model: config.anthropicModel,
  });
  const tools = buildToolRegistry();
  const ledger = new Ledger(repo);
  // F6: the orchestrator decomposes complex tasks into typed-agent subtasks.
  const planner = new ModelPlanner(model);
  // F5: agent memory (recall into prompts, episodic write-back).
  const memory = new RepositoryMemoryStore(repo);
  // F4: event bus + observability + billing + the control-plane API.
  const events = new InMemoryEventBus();
  const observability = new Observability(repo, ledger);
  const payments = new StripePaymentProvider({
    apiKey: config.stripeApiKey,
    webhookSecret: config.stripeWebhookSecret,
    successUrl: config.checkoutSuccessUrl,
    cancelUrl: config.checkoutCancelUrl,
  });
  const controlPlane = new ControlPlane({
    repo,
    queue,
    ledger,
    observability,
    payments,
    events,
  });

  return {
    workerDeps: {
      queue,
      repo,
      model,
      tools,
      ledger,
      allowlistDomains: config.allowlistDomains,
      planner,
      events,
      memory,
    },
    controlPlane,
  };
}

export { startWorker } from './worker/worker';
export { createControlPlaneServer } from './api/server';
