// Composition root. Wires production adapters into the runtime/worker and the
// Control Plane.
//
// Planes:
//   - Control Plane: the ControlPlane API (src/api) creates runs, exposes status
//     + observability, and manages the DLQ.
//   - Execution Plane: the worker (startWorker) drains the queue and runs agents.
//   - Data Plane: the Repository (runs, steps, memory, audit).

import { loadConfig } from './config';
import { ToolRegistry } from './tools/registry';
import { httpRequestTool } from './tools/httpRequest';
import { codeExecTool } from './tools/codeExec';
import { webSearchTool } from './tools/webSearch';
import { readDocumentTool } from './tools/document';
import { TavilySearchProvider } from './adapters/search.tavily';
import { PerplexitySearchProvider } from './adapters/search.perplexity';
import { RichDocumentParser } from './adapters/documents.rich';
import { WorkerDeps } from './worker/worker';
import { PrismaRepository, PrismaClientLike } from './adapters/repo.prisma';
import { BullMQQueue } from './adapters/queue.bullmq';
import { AnthropicModelProvider } from './adapters/model.anthropic';
import { ClaudeSubscriptionModelProvider } from './adapters/model.claudeSubscription';
import { OfflineModelProvider } from './adapters/model.offline';
import { ModelProvider } from './ports/model';
import { ModelPlanner } from './orchestrator/planner';
import { RedisEventBus } from './adapters/events.redis';
import { PgVectorMemoryStore, RawSqlClient } from './adapters/memory.vector.pg';
import { HashEmbedder } from './adapters/embedder.hash';
import { SubprocessSandbox } from './adapters/sandbox.subprocess';
import { Observability } from './observability/metrics';
import { ControlPlane } from './api/controlPlane';
import { RegexPiiMasker } from './security/pii';

export function buildToolRegistry(): ToolRegistry {
  const tools = new ToolRegistry();
  tools.register(httpRequestTool);
  tools.register(codeExecTool);
  tools.register(webSearchTool);
  tools.register(readDocumentTool);
  return tools;
}

export interface App {
  workerDeps: WorkerDeps;
  controlPlane: ControlPlane;
}

export function buildApp(): App {
  const config = loadConfig();

  // Prisma client is generated by `npx prisma generate`; require lazily so this
  // module compiles before generation.
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { PrismaClient } = require('@prisma/client');
  const prisma = new PrismaClient();
  const repo = new PrismaRepository(prisma as PrismaClientLike);

  const queue = new BullMQQueue({ redisUrl: config.redisUrl });
  // Brain selection: Max subscription (OAuth token) → API key → offline fallback.
  let model: ModelProvider;
  if (config.claudeOauthToken) {
    model = new ClaudeSubscriptionModelProvider({
      model: config.anthropicModel,
      timeoutMs: config.claudeCliTimeoutMs,
    });
  } else if (config.anthropicApiKey) {
    model = new AnthropicModelProvider({
      apiKey: config.anthropicApiKey,
      model: config.anthropicModel,
      baseURL: config.anthropicBaseUrl || undefined,
    });
  } else {
    model = new OfflineModelProvider();
  }
  const tools = buildToolRegistry();
  // F6: the orchestrator decomposes complex tasks into typed-agent subtasks.
  const planner = new ModelPlanner(model);
  // F5: vector long-term memory (pgvector). HashEmbedder (dim 256) matches the
  // AgentMemory.embedding column; swap for OpenAIEmbedder with a dimension migration.
  const memory = new PgVectorMemoryStore(prisma as RawSqlClient, new HashEmbedder());
  // F3: isolate for code_exec (Linux namespaces + rlimits). Swap for
  // DockerSandbox where a container runtime + images are available.
  const sandbox = new SubprocessSandbox();
  // PRD §3 integration tools. Provider cascade: Perplexity (preferred) → Tavily.
  // Used by the agent-os web_search tool on tool-capable paths (API path); the
  // subscription/CLI path uses the CLI's built-in WebSearch instead (see runtime
  // capabilities + model.claudeSubscription).
  const search = config.perplexityApiKey
    ? new PerplexitySearchProvider({ apiKey: config.perplexityApiKey })
    : config.tavilyApiKey
      ? new TavilySearchProvider({ apiKey: config.tavilyApiKey })
      : undefined;
  // Doc-1 file handling: docx/pdf/xlsx + text/csv/json, honest actionable errors.
  const documents = new RichDocumentParser();
  // Mask PII before prompts leave for external LLMs.
  const pii = new RegexPiiMasker();
  // F4: cross-process event bus (Redis pub/sub) + observability + control-plane API.
  const events = new RedisEventBus(config.redisUrl);
  const observability = new Observability(repo);
  const controlPlane = new ControlPlane({ repo, queue, observability, events, documents });

  return {
    workerDeps: {
      queue,
      repo,
      model,
      tools,
      allowlistDomains: config.allowlistDomains,
      planner,
      asyncChildren: true,
      events,
      memory,
      sandbox,
      search,
      documents,
      pii,
    },
    controlPlane,
  };
}

export { startWorker } from './worker/worker';
export { createControlPlaneServer } from './api/server';
